### ISSUE TITLE
Minor issue with get users API

### ISSUE THREAD

**Issue by shankey28** [eddiejaoude/node-express-course#12]
API is getting all users, looks like we can remove "id" attribute from response json

## Before:

app.get("/users", function (req, res) {
    res.json({
        success: status,
        message: message,
       **id: req.params.id,**
        users: mockUserData,
    });
});

## After:

app.get("/users", function (req, res) {
    res.json({
        success: status,
        message: message,
        users: mockUserData,
    });
});

**Comment by eddiejaoude** [comment]
Oh yes, there will be no request `id` for the user list
